In [1]:
import pandas as pd

In [3]:
df_15_2017 = pd.read_csv(
    r"C:\Users\joabd\Desktop\Projects\ML Project\data\raw\cycle_counts\2017_2024\cycle_count_15min.csv"
)

df_15_2025 = pd.read_csv(
    r"C:\Users\joabd\Desktop\Projects\ML Project\data\raw\cycle_counts\2025\rad_2025_01_15min.csv"
)

df_15_2026 = pd.read_csv(
    r"C:\Users\joabd\Desktop\Projects\ML Project\data\raw\cycle_counts\2026\rad_2026_01_15min.csv"
)

In [4]:
df_15_2017.tail(5)

,datum,uhrzeit_start,uhrzeit_ende,zaehlstelle,richtung_1,richtung_2,gesamt
1620778,2024.12.31,23:45,00:00,Arnulf,0.0,1.0,1.0
1620779,2024.12.31,23:45,00:00,Erhardt,3.0,3.0,6.0
1620780,2024.12.31,23:45,00:00,Hirsch,0.0,0.0,0.0
1620781,2024.12.31,23:45,00:00,Kreuther,0.0,0.0,0.0
1620782,2024.12.31,23:45,00:00,Olympia,5.0,0.0,5.0

In [8]:
df_15_2025.head(5)

,datum,uhrzeit_start,uhrzeit_ende,zaehlstelle,richtung_1,richtung_2,gesamt
0,2025.01.01,00:00,00:15,Arnulf,1,0,1
1,2025.01.01,00:15,00:30,Arnulf,3,0,3
2,2025.01.01,00:30,00:45,Arnulf,5,0,5
3,2025.01.01,00:45,01:00,Arnulf,3,0,3
4,2025.01.01,01:00,01:15,Arnulf,3,1,4

In [9]:
df_15_2026.head(5)

,datum,uhrzeit_start,uhrzeit_ende,zaehlstelle,richtung_1,richtung_2,gesamt
0,2026.01.01,00:00,00:15,Arnulf,0,0,0
1,2026.01.01,00:15,00:30,Arnulf,2,0,2
2,2026.01.01,00:30,00:45,Arnulf,0,0,0
3,2026.01.01,00:45,01:00,Arnulf,0,1,1
4,2026.01.01,01:00,01:15,Arnulf,0,0,0

In [10]:
df_15_2025["zaehlstelle"].unique()

<StringArray>
['Arnulf', 'Olympia', 'Hirsch', 'Erhardt']
Length: 4, dtype: str

In [11]:
df_15_2026["zaehlstelle"].unique()

<StringArray>
['Arnulf', 'Kreuther', 'Olympia', 'Hirsch', 'Erhardt']
Length: 5, dtype: str

In [12]:
df_15_2017["zaehlstelle"].unique()

<StringArray>
['Arnulf', 'Erhardt', 'Hirsch', 'Kreuther', 'Margareten', 'Olympia']
Length: 6, dtype: str